[package]
name = "minimax"
version = "0.0.2"
authors = [ "Samuel Fredrickson <samfredrickson@gmail.com>" ]
description = "Generic implementations of Minimax."
documentation = "http://kinghajj.github.io/doc/minimax/"
repository = "http://github.com/kinghajj/minimax-rs.git"
readme = "README.md"
keywords = ["ai", "game", "minimax", "negamax"]
license = "MIT"

[dependencies]
rand = "0.4.*"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "negamax"
harness = false

[profile.test]
opt-level = 3
